# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import sender.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
            ],
            managers=[
                ('objects', sender.managers.CustomerManager()),
            ],
        ),
    ]
