# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-02 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sender.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Customer')),
            ],
            managers=[
                ('objects', sender.managers.ThemeManager()),
            ],
        ),
    ]
