# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sender.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0002_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Customer')),
            ],
            managers=[
                ('objects', sender.managers.ThemeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='theme',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='themecustomer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.Theme'),
        ),
    ]
