# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-02 13:45
from __future__ import unicode_literals

from django.db import migrations
import sender.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20230202_1342'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='theme',
            managers=[
                ('objects', sender.managers.ThemeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themecustomer',
            managers=[
            ],
        ),
    ]
